BOARD_TAG    = uno
# BOARD_TAG    = nano
# MCU = atmega328p
ARDUINO_LIBS = Time DS1307RTC Wire Adafruit_NeoPixel
AVRDUDE_OPTS = -V -v -v
#MONITOR_PORT = /dev/tty.SLAB*
# ARDUINO_QUIET = 1

include ${ARDMK_DIR}/Arduino.mk
