BOARD_TAG    = woodenbits
# BOARD_TAG    = uno

ISP_PROG = usbasp

BOARDS_TXT = wbboards.txt

ARDUINO_LIBS = Time DS3232RTC Wire Adafruit_NeoPixel
AVRDUDE_OPTS = -V

CXXFLAGS_STD = -std=gnu++11 -fno-threadsafe-statics

# ARDUINO_QUIET = 1

include ${ARDMK_DIR}/Arduino.mk
